### ISSUE TITLE
Read documentation about Custom Clients

### ISSUE THREAD

**Issue by yuriaru** [RutgersGRID/hubs#1]

**Comment by MuhammadUzairDocs** [comment]
I have read through the Custom Client Documentation.
After cloning the Repository to my PC I was able to cd into hubs-cloud and run npm ci
After running npm run login, I'm not sure what website URL I am supposed to use. I assume its of a server that I am to run on my machine. But not really sure how to do that.

after logging in using my scarlet mail and authenticating when I run "npm start" I have an error "Error fetching Hubs Cloud config "unauthorized".
I think its since I am using the URL that is provided when I run npm run login "hubs.mozilla.com"

**Comment by MuhammadUzairDocs** [comment]
Closed
