### ISSUE TITLE
Connect Hubs client VM with Reticulum server VM

### ISSUE THREAD

**Issue by yalegria** [RutgersGRID/hubs#22]

**Comment by yalegria** [comment]
@Voxelghiest the image below depicts very nicely all the components of the ecosystem

![System_Overview](https://user-images.githubusercontent.com/7467260/170288688-d57ef769-d0b7-41ff-b437-e82d4e16d667.png)

**Comment by Voxelghiest** [comment]
# Mozilla Hubs Installation Procedure (Cont.)
This tutorial assumes you have completed both part 1 (Reticulum, #37) and part 2 (Dialog, #24) first, and that your Ubuntu server has internet access.

*This tutorial is still a work-in-progress. I will continue to add to it as I develop the process myself.*

## 3. Hubs Client & Admin
The Hubs Client is the component of Hubs that serves the application to the end-user. It also handles administrative services through Hubs Admin.

### 3.1. Setup Hubs Client
Return to the parent directory containing both Reticulum and Dialog from the previous parts. Download Hubs Client from the Mozilla GitHub (which also includes Hubs Admin) and move into the new directory:
```shell
$ git clone https://github.com/mozilla/hubs
$ cd hubs
```
As an aside, at this point your overall file structure should look like this:

<img width="113" alt="pic1 - directory structure" src="https://user-images.githubusercontent.com/72222982/183673388-39c957cd-8143-4e93-94bc-115a37f82d9a.png">

Once inside the Hubs Client directory, install its dependencies using NodeJS:
```shell
$ npm ci
```
The installation will take a while and may give a number of warnings, but as long as no fatal errors occur, you should be alright. The final output should look like this:

<img width="801" alt="pic2 - hubs npm ci" src="https://user-images.githubusercontent.com/72222982/183673426-dec30c1b-79df-48b0-aa96-ef5dd5d81edf.png">

As with Dialog in the last part of this tutorial, Hubs requires a pair of certificates in order to serve itself over HTTPS. As before, these certificates are located in the `priv` folder of Reticulum, and must be copied over and renamed. This can be done by running the following commands inside the *Hubs Client* directory (not Reticulum):
```shell
$ cp ../reticulum/dev-ssl.cert ./certs/cert.pem
$ cp ../reticulum/dev-ssl.key ./certs/key.pem
```
This copies the certificates over and renames them appropriately.

The last change you must make is to edit the server's startup parameters. Return to the Hubs Client folder, open the file `package.json` in a text editor, and on line 19, add the following flags to the `"local"` npm script:
```json
    "local": "webpack-dev-server --mode=development --env.localDev --no-devtool --progress --https --cert certs/cert.pem --key certs/key.pem",
```
`--no-devtool` is needed to stop the server from generating a source map on startup, which for some reason causes it to crash. `--https`, `--cert`, and `--key` set up the HTTPS certificates. The `--progress` flag is simply for convenience.

### 3.2. Setup Hubs Admin
Hubs Admin is contained in the `admin` subfolder within the Hubs Client directory, but the setup process for it is almost identical. From the Hubs Client directory, move into Hubs Admin and install its dependencies:
```shell
$ cd admin
$ npm install
```
Like before, the installation will take a long time, and the output should look something like this:

<img width="801" alt="pic3 - admin npm install" src="https://user-images.githubusercontent.com/72222982/183673468-c8185247-cd60-4b56-b0c9-9fab158ec3ba.png">

Then, like before, open the file `package.json` and add the `--no-devtool` and `--progress` flags to the `"local"` npm script.

**Comment by Voxelghiest** [comment]
I've just added the first version of the process to set up Hubs Client and Hubs Admin. Under the current process, once everything is set up, I can run Reticulum, Dialog, and Hubs Client in tandem, and the Hubs Client server starts up without issues:

<img width="800" alt="pic4 - server startup" src="https://user-images.githubusercontent.com/72222982/183674673-cbc566fa-b9a7-4093-ba1d-b1a67b006b49.png">

Then, by going to `https://<server-ip>:4000/?skipadmin` in my browser, I can access the Hubs Client:

![Screen Shot 2022-08-09 at 10 29 27 AM](https://user-images.githubusercontent.com/72222982/183675556-edc4affa-ce4e-4bb9-a99c-0fe5ca164417.png)

The only problem is that, as the screenshot above shows, the https certificates are considered invalid by both my browser and by the server itself. In the debug console, all the failed GET requests were made to port 8080 from port 4000, which are the ports for the Hubs Client and Reticulum servers, respectively. This is still good news, because it means that the two servers are indeed communicating with each other, but I'm unsure how to make the certificates valid so the page can be loaded. I thought that the pair of certificates that come with the Reticulum repo (in the `priv` folder) would work, but maybe I need to generate them myself somehow?

**Comment by Voxelghiest** [comment]
[This discussion](https://github.com/mozilla/hubs/discussions/5173) I've found on the Reticulum repo might be of some use. It seems to be discussing a similar issue with self-signed certificates.

**Comment by Voxelghiest** [comment]
Out of curiosity, I tried accessing the Hubs Client server directly by going to `https://<server-ip>:8080`, skipping the forwarding that Reticulum does, but the result was the same:

![Screen Shot 2022-08-09 at 10 49 08 AM](https://user-images.githubusercontent.com/72222982/183680733-3488deeb-581f-454e-b93a-ef00c0a13eb3.png)

Either way, it's good information to know.

**Comment by yalegria** [comment]
The architecture is a little different from the title of this ticket. We are currently spinning all the Hubs components from the same virtual machine.
