### ISSUE TITLE
New Rutgers Virtual Worlds documentation page.

### ISSUE THREAD

**Issue by yalegria** [RutgersGRID/hubs#45]

**Comment by Voxelghiest** [comment]
I've decided that it is easiest for me to just bundle the HTML code for the new page and the images I used into a single ZIP file, which I am attaching here:
[RVW Documentation Page.zip](https://github.com/RutgersGRID/hubs/files/9454803/RVW.Documentation.Page.zip)

The HTML code has `<img/>` tags in all the places where the images are supposed to go, so it should be easy to insert them at the correct locations. The source names for the `<img>` tags match the names of the image files in the folder.

I noted that the original documentation page had a table of contents, but I assume it was made with some sort of program, so I decided not to include it because it would have taken a while to type out myself.

**Comment by yalegria** [comment]
@Voxelghiest I was able to unzipped the file. It looks good.  This will help me create the pages at the website.
